name: test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 8
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2
      - run: gradle check
      - run: gradle checkLicense
